version: '3'

services:
  nest-app:
    build:
      context: ./my-new-app
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    volumes:
      - ./my-new-app:/my-new-app

  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6
    restart: unless-stopped

volumes:
  postgres-data:
